# hydra config
hydra:
  run:
    dir: ${paths.log_path}
  job:
    chdir: false

# Path
paths:
  video_path: /workspace/data/raw
  log_path: logs/sam3d-body/${now:%Y-%m-%d}/${now:%H-%M-%S}
  result_output_path: /workspace/data/sam3d_body_results

# Model
model:
  root_path: /workspace/code/ckpt/sam-3d-body-dinov3
  checkpoint_path: ${model.root_path}/model.ckpt
  mhr_path: ${model.root_path}/assets/mhr_model.pt

  # detector_name: yolov8n
  # segmentor_name: sam_vit_b
  fov_name: moge2

visualize:
  save_focal_length: false
  save_mesh_ply: false
  save_mesh_overlay: true
  save_bbox_image: true
  save_3d_mesh: false
  save_3d_keypoints: true
  save_together: true

infer:
  conf_thres: 50.0
  keep_frames: true
  num_inference_steps: 4
  gpu: [0, 1] # 指定使用的 GPU 列表
  workers_per_gpu: 2 # 每个 GPU 使用的工作线程数,3090 建议 2

dataset:
  recursive: true
